#!/bin/bash
######################################################################
# Author: jrjbear@gmail.com
# Date: Thu Jan 30 12:07:38 2014
# File: account
#
# Usage: account userid
# Description: Print account information according to the given userid
######################################################################


# Use `read' instead of `for' loop to get fields because they may
# contain blanks in username. Use process substitution instead of
# pipes to while since the latter will run in a subshell (which
# hides the variable inside `while').
while read line; do
    user="${line%%:*}"
    name="${line##*:}"
    user_uid="${line%:*}"
    uid=${user_uid#*:}
    acc[${uid}]="${user}:${name}"
done < <(cut -f1,3,5 -d: /etc/passwd)

if ! echo $1 | grep '^[0-9]\+$' > /dev/null; then
    echo "Usage: account userid" >&2
    exit 1
fi

if [[ -z "${acc[$1]}" ]]; then
    echo "User ID $1 not found" >&2
    exit 1
fi

echo "User ID $1 is ${acc[$1]%:*}, whose full name is ${acc[$1]#*:}"
echo "There are currently ${#acc[@]} user accounts on the system"